import = ["~/.config/alacritty/themes/tokyo-night.toml"]

[font]
normal = { family = "MesloLGM Nerd Font" }
size = 15.0

[window]
decorations = "Full"
opacity = 0.9
blur = true

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001bf" },
  { key = "Left", mods = "Alt", chars = "\u001bb" },
  { key = "D", mods = "Command", chars = "\u0002%" },
  { key = "D", mods = "Command|Shift", chars = "\u0002\""},
  { key = "W", mods = "Command", chars = "\u0002x" },
]

